name: Generate Snake


on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 */12 * * *" # run automatically every 12 hours


jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Generate a snake game from my commit-history
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # push the content of dist/ to the 'output' branch
      # the content will be available at https://raw.githubusercontent.com/tomhea/tomhea/output/ , or as github page
      - name: push github-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
